### ISSUE TITLE
Aplicar los temas de las semanas 1-5

### ISSUE THREAD

**Issue by L-Jmd** [Proyectos-UTP/Proyecto_POO#12]
Informar todo acerca de los temas de las semanas 1-5 y sus posibles aplicaciones al proyecto aquí. No hay necesidad de implementar todos los temas, solo los que veas adecuados. De no aplicar un tema al proyecto, dejar un comentario justificando la razón de ello.

- [x] Semana 1
- [x] Semana 2
- [ ] Semana 3
- [ ] Semana 4
- [ ] Semana 5

**Comment by L-Jmd** [comment]
Ejemplo de justificación de porque no se aplica un tema al proyecto:
- Semana 1: El tema visto en la semana 1 es la introducción al diagrama UML y un repaso de lo basico de POO, es decir, aspectos que ya están implementados en el proyecto actualmente como constructores, clases por objectos, etc.

**Comment by FBN-64** [comment]
La semana 2 es muy similar a la semana anterior, sigue mencionando constructores, métodos, y los tipos de atributos que podemos asignar. De momento está asignado en el proyecto, pero debe profundizarse un poco más con las otras semanas.

**Comment by FBN-64** [comment]
La semana 3 trata sobre las relaciones que hay entre clases. De momento solo se tiene implementado la relación de herencia, pero se implementarán más según nos sea conveniente.
